
@hostname=localhost
@port = 5620
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}



POST http://{{host}}/print HTTP/1.1
content-type: {{contentType}}

{
    "text": "hola \n asdfiasdfaisdfasdf \nasdf asdf asdf "
}


### 



POST http://{{host}}/cut HTTP/1.1
content-type: {{contentType}}

{
}